"""api-cowork

Revision ID: 45dedc1c337d
Revises: 
Create Date: 2025-04-02 00:12:50.276456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45dedc1c337d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passw', sa.String(length=100), nullable=False))
        batch_op.alter_column('fecha_registro',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_column('pass')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pass', mysql.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('fecha_registro',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_column('passw')

    # ### end Alembic commands ###
